### ISSUE TITLE
Path issues when running in PHPStorm

### ISSUE THREAD

**Issue by RomanSparhandy** [xjamundx/jshint-junit-reporter#12]
When running jshint-junit-reporter in PHPStorm on Win 7, the paths don't match so no failures are written into the report file. I already implemented a fix for this, so if you are interested I'll be happy to contribute it.

**Comment by xjamundx** [comment]
I've moved to using eslint, but would happily accept a PR with tests.

**Comment by udjamaflip** [comment]
Do you have steps to replicate and details of the environment/PHPStorm version? I don't encounter this issue on PHPStorm 8.0.1 with Win 10
